# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Python app to Azure Web App - gilopezESumm

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python version
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'

    - name: Build using AppService-Build
      uses: azure/appservice-build@v2
      with:
        platform: python
        platform-version: '3.8'
        
    - name: Install Custom Dependencies(fastapi)
      run: pip install fastapi
      
    - name: Install Custom Dependencies(uvloop)
      run: pip install uvloop
      
    - name: Install Custom Dependencies(httptools)
      run: pip install httptools
      
    - name: Install Custom Dependencies(uvicorn)
      run: pip install uvicorn
      
    - name: Install Custom Dependencies(transformers)
      run: pip install transformers[torch]

    - name: 'Deploy to Azure Web App'
      uses: azure/webapps-deploy@v2
      with:
        app-name: 'gilopezESumm'
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_73cb1715a50c47359d35312fa4913cca }}